apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockauth
  labels:
    app: blockauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockauth
  template:
    metadata:
      labels:
        app: blockauth
    spec:
      containers:
      - name: blockauth
        image: blockauth:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 500m
